---
title:
  # Title must be 150 characters or less
  "Examining the explanatory model of the cultural continuity of an archaeological site in Taiwan"
author:
  - name: Liying Wang
    affiliation: '1'
    # If corresponding author (only one corresponding author per manuscript)
    email: liying15@uw.edu
affiliation:
  - id: '1'
    department: Department of Anthropology
    institution: University of Washington
    city: Seattle
    state: Washington
    country: USA
output: rticles::plos_article
#csl: plos.csl
bibliography: myfile.bib
---

# Introduction {-}

In this paper, I will focus on a debate about whether the separate cultural layers in Kiwulan (KWL) site in Northern Taiwan belong to the same prehistoric ethnic group. The KWL site is located at Ilan city and near a riverside at the northern margin of the Ilan plain in Northeastern Taiwan. The site was excavated during 2001 to 2003 by the Department of Anthropology of National Taiwan University [@Chen2007]. According to the archaeological remains, the site can be divided into a lower culture layer and an upper culture layer, dating from 1300B.P. to 800B.P. and 600B.P. to 100B.P.respectively based on radiocarbon dates. However, there is a debate about whether the archaeological remains from both layers belong to the same culture or not, because the archaeological remains show both similar and different patterns. Chen (2007) argued that these two layers belong to the same culture based on similar pattern of artifacts. However, Chiu (2004) stated that they belong to different culture or ethnic group due to the distinct style of mortuary practice. The difference of these explanations shows distinct explanatory models in terms of archaeological evidence. The following sections I will examine these two explanations based on archaeological evidence, explore the philosophical theories behinds them, discuss their strength and weakness, and then conclude that Chen's argument might be more appropriate in this case. However, both explanations still need clear theoretical framework, and the combination of these two models might be a better solution to this debate. 

# Archaeological evidence {-} 

The excavation of Kiwulan site covered an area of 2,800 sqm and revealed hundreds of thousands of artifacts from a total of 262 archaeological excavation areas. The following I will introduce the archaeological evidence found in these layers respectively.

1. Lower culture layer (1300-800 B.P)

The archaeological evidence include a wide variety of pottery, post holes, slabs which are associated with households, 35 burials, few iron knifes and artifacts, grinding stones, slabs, imported ornaments such as glass beads, agate beads, metal bracelet, glass earrings, fauna remains such as deer and pigs. There is no much evidence relates to practices of agriculture. In addition, hunting and gathering are believed as the main subsistence in this period. 
For the pottery, there are different kinds of shape and form, including bowls, vessels, and pots. The most common type of pottery is the pottery with stamped geometric decoration.  Although there are many types of pottery in the living area, only geometric decoration pottery and plain vessels found in burials as burial goods. In addition to pottery, imported ornaments are often used as burial goods. For the burials, secondary burial is the most common type, and slabs were used to serve as funerary utensils. The people abandoned this settlement around 800B.P due to the environmental change [@Chen2007]. 

2. Upper culture layer (600-100 B.P.)

The archaeological remains found in this period were more than lower culture layer. The archaeological evidence includes pottery, imported ceramics and stonewares, wooden artifacts such as table wares and tools, grinding stones, metal artifacts such as knives and points, imported ornaments such as glass beads, agates beads, and metal bracelets, pipes which made of stone, clay, and metal, local ornaments made of animal bones, shells, and wood, and fauna assemblage. In addition to artifacts, 90 burials and wooden pole structures were also excavated. These wooden poles were found aligned in a north-south direction with construction marks, which were interpreted as the remains of house structures. 
The distribution of features shows that the cemetery is located at the north part of house structures, which indicates the settlement was organized in some order. According to historical records, this settlement was believed as the biggest settlement in the 17th century [@Nakamura1938]. The potteries were usually decorated with geometric design, which is similar to the pottery in earlier period. For the burials, the common funerary utensils were wooden boards. In addition to imported ornaments, imported ceramics were also the common burials goods [@Chen2007]. 

# Links between evidence and behavior {-}

Chen (2007) focused on the similar archaeological remains in both layers. He pointed out the similarity of burial goods, such as local pottery, glass beads, and agate beads. Although the forms and shapes of beads are not completely the same in both layers, he argued that the distribution and pattern of burial goods is similar. Agate beads and glass beads usually served as necklaces on deceased, and some small beads reveal that they were part of the decoration of clothes. In addition to beads, pottery is the common burial good in both layers. He states that the people from these two periods have similar mortuary practice based on the distribution of burial goods, especially for pottery and glass beads. Moreover, the pattern of pottery in both layers shows the similar surface treatment, stamped geometric decoration, which also indicates the same system of decoration and technique for making pots. For the households, both periods were found post holes and wooden poles, which indicates they might have similar household form and structure. Chen linked the archaeological evidence with human behaviors at household level, and viewed these human behaviors as an entity, which reflects settlement level. He stated that the similarity of artifacts of two cultural layers indicates the cultural transmission in a singular culture, in which cultural elements transmits from people to people, and from generation to generation.        

On the other hand, Chiu (2004) stresses the difference between these two layers mainly based on mortuary practice. The common burial in lower cultural layer is secondary burials and the people usually used slabs as funeral utensils; however, most burials in upper culture layer are primary with bodies in flexed position. Moreover, wood is the common funeral utensil in upper culture layer rather than slabs. Although people from both layers used beads as burial goods, the forms and shapes shows slightly difference. For example, the lower culture layer was found glass earrings, which is absent in upper culture layer. Based on Person (1999) arguments, he stated that mortuary practices are social and political behaviors. Mortuary practices and associated burial goods are not only artifacts, but also rules and custom related to the core element of a culture [@Pearson1999]. Besides, he believed that mortuary practice usually links to the ritual, the worldview, and the view of life and death of an ethnic group. The viewpoints for mortuary practice of an ethnic group seldom change and will pass down from generation to generation unless they face significant influence. Therefore, he stated that the people from two layers belong to different cultures, because their mortuary practices are different, and there is no relevant evidence shows any factor that will affect the culture change if they are the same ethnic group. Regarding the similar burials goods found from both layers, he argued that the burial goods such as glass beads were imported materials, which indicates the common interaction between Northern Taiwan and Southeast China in the prehistoric period rather than the preference of a culture [@Chiu2004].

# Discussion {-}

1. Context of the monograph’s explanatory model

The same culture hypothesis is based on the similar human practice on daily life, such as making pattern, living, and mortuary practice. This viewpoint stresses that we should examine the artifacts as a whole. Chen stated that if we focus on singular artifact, we might think these remains belong to different groups. But when examining all of the archaeological remains together, both layers indicate similar pattern of artifacts and shows some continuity of cultural element. As a director of excavation of Kiuwlan site, Chen prefers to interpret the archaeological remains as a whole, and try to provide an explanation for these two cultural layers. Also, Chen completed his PhD program at Graduate school of social and cultural studies of Kyushu University in Japan around 1999, which tends to interpret the archaeological evidence based on topology and culture-historical approach. This background influenced him to focus on the similar cultural elements, and the relationship of cultural elements and the preference of ethnicity.        

On the other hand, different culture hypothesis assumes that mortuary practice reflects the view of life and death of an ethnic group, which is the core element in a culture and seldom changes with time. Chiu argues that although the style of pottery or households show the similar pattern in both layers, these cultural elements tend to be influenced by other culture through frequent interaction. This approach emphasizes that mortuary practice can be viewed as ritual, which reflects the most important part of a culture. Chiu is interested in mortuary practice and human remains since he was an graduate student, which leads to such interpretation based on burials. Although he graduated from the same PhD program as Dr. Chen, Chiu was influenced more by explanatory approach to archaeology. This background leads to the foci of the scientific method and hypothesis testing. In this case, Chiu used quantitative method to examine the burials goods, human remains, and forms of mortuary practice in order to synthesis the discussion of the culture change of Kiwulan site.             

2. Relevant philosophy of science

I think Chen's (2007) argument is based on the inference of best explanation, because he examined all of the evidence found in these two periods, and thought the explanation that two periods belongs to the same culture can fit most evidence he found so far. As Lipton (2000) mentioned, a good explanation should require a cause that can explain both the fact and other possible phenomenon, and should explain as many phenomena as possible. I think Chen's argument fulfills these requirements, because his argument can explain different type of artifacts instead of singular evidence. In addition, Chen focuses on the culture element of these two layers, which indicates there is a culture transmission from generation to generation. This assumption to some extent is based on the culture transmission theory, which stresses the inheritance of cultural elements to explain human variation [@Shennan2008]. The cultural transmission theory can be viewed as unification, which assumes we can use few core patterns to describe a wide range of phenomena. In his case, the inheritance of cultural elements is the common pattern we can found in most societies, and it serves as an explanation to interpret the similarity of two culture layers.  

On the other hand, I think Chiu’s (2004) argument is based on the D-N model and causal mechanism. D-N model relies the logic connection and hypothesis building. Chiu's explanation shows that his argument is based on the statement that the ritual is the core cultural element of any human culture and seldom changes with time unless they face significant influence. Second statement is that every ethnic group has their distinct ritual, and the mortuary practice reflects a kind of ritual. Therefore, by examining the mortuary practice, he stated that it is possible to understand the culture change of an ethnic group. Because there is no evidence shows any factor that affects the change in mortuary practice if these two periods belongs to the same culture. By applying the D-N model, he infered that the people from two layers belong to different group. Besides, I think his argument is also relative to causal mechanism proposed by Glennan, who distinguished different narrative explanations in terms of explanatory grains [@Glennan2010]. In this case, Chiu explained the human remains and mortuary types in a fine-grained way, and interpret the relationship between mortuary practices and ethnic group in a coarse-grained way.

3. Critique

I think both arguments need clear theoretical framework to support their inferences. Although Chen's argument can explain most archaeological reamins from the site, there is no explanation for the connection between the lower culture layer and upper culture layer. For example, what kind of cultural element can represent an ethnic group, and why these elements can be transmitted from generation to generation, or from person to person without change? In other words, it is necessary to further examine the mechanism of cultural transmission from lower culture layer to upper culture layer. On the other hand, Chiu's argument provides the mechanism behinds the mortuary practice and culture change, which connects the archaeological evidence with the concept of ethnicity. However, his explanation only relies on the mortuary practice, which overlooked other possible phenomenon that can provide clues for the culture continuity. How can we interpret the culture continuity only based on mortuary practice is the question and it needs strong theoretical framework and modeling test to support it. Therefore, I think Chiu's argument should also consider other evidence in order to give a better explanation. Both arguments show their strengths and flaws, and I proposed that the combination of these two explanatory models might provide a better explanation. 

# Conclusion {-}

The culture continuity of Kiwulan site is an important topic in Taiwan, because if two culture layers belong to the same ethnic group, then the site can provide a good source to research the long term change of a culture. Chen's model, which assumes that we can view these two layers as a same culture, provides an appropriate explanation based on most archaeological evidence and the similar cultural elements. However, his explanation lacks of the explanation of mechanism for the culture transmission. On the other hand, although Chiu's argument only focuses on the mortuary practice, he examines the evidence both in fine and coarse-grained way. 

I think the combination of these two approaches can provide a better explanation for the culture continuity. We can examine the relationship of each type of archaeological evidence and associated human behavior in a fine-grained way by scientific methods, such as DNA analysis for human remains, or technical choice in pottery production. In a course-grained way, we can explore the mechanism of culture change in a ethnic group based on the general pattern identified by archaeologists from other places and then formulate a model to test the archaeological evidence from Kiwulan site. Based on Glennan's causal mechanism approach, we can combine Chen's culture transmission theory and Chiu's hypothesis testing in order to obtain a better understanding of the culture continuity of Kiwulan site.

# Reference {-}